apiVersion: v1
kind: Service
metadata:
  name: godns
spec:
  type: NodePort
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
    nodePort: 30053
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 30053
  selector:
    run: godns
