apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: godns
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: godns
    spec:
      containers:
      - name: godns
        image: sample/godns:1.0
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
